# Generated by Django 4.1.7 on 2023-04-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_name_alter_delivery_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
