# Generated by Django 4.1.7 on 2023-04-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_item_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='comment',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
