# Generated by Django 4.1.7 on 2023-04-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_delivery_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='images/dishes/'),
        ),
    ]
