# Generated by Django 4.1.7 on 2023-04-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_dish_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='static/images/dishes/'),
        ),
    ]
