# Generated by Django 4.1.7 on 2023-04-12 08:44

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_dish_imagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='imagefile',
            field=models.ImageField(null=True, upload_to=main.models.dish_image_path),
        ),
    ]
