# Generated by Django 4.1.7 on 2023-04-12 09:03

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_dish_imagefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='image',
        ),
        migrations.AddField(
            model_name='dish',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='imagefile',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.dish_image_path),
        ),
    ]
