# Generated by Django 4.1.7 on 2023-04-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_category_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_Url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image_Url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
